### ISSUE TITLE
[BUG]: Nonfatal Error caused by use-of-uninitialized-value (jhead v3.06)

### ISSUE THREAD

**Issue by WorldExecute** [Matthias-Wandel/jhead#53]
# Crash Inputs
Here is the files (14 in total) that trigger the error - [crashes.zip](https://github.com/Matthias-Wandel/jhead/files/9198972/crashes.zip)

# Bug Description:
When executing jhead-3.04 (release version) with the file inputs, the program terminates with Nonfatal Error shown below.

```
Nonfatal Error : './out-msan/crashes/id:000013,sig:06,src:000113+000119,op:splice,rep:8' Extraneous 41 padding bytes before section E1

Nonfatal Error : './out-msan/crashes/id:000013,sig:06,src:000113+000119,op:splice,rep:8' Extraneous 15 padding bytes before section C1

Error : Premature end of file?
```

Then I apply MSan (Memory Sanitizer ) to check for memory errors and the error report is as follows.
```
Nonfatal Error : './out-msan/crashes/id:000013,sig:06,src:000113+000119,op:splice,rep:8' Extraneous 41 padding bytes before section E1
Uninitialized bytes in MemcmpInterceptorCommon at offset 0 inside [0x702000000002, 4)
==3762==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x42c39c in bcmp (/home/camsyn/bench/cov/jhead/jhead+0x42c39c)
    #1 0x49e034 in ReadJpegSections jpgfile.c:288:25
    #2 0x49edb6 in ReadJpegFile jpgfile.c:384:11
    #3 0x498332 in ProcessFile jhead.c:914:10
    #4 0x498332 in main jhead.c:1770:13
    #5 0x7f0a877c00b2 in __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:308:16
    #6 0x41c3bd in _start (/home/camsyn/bench/cov/jhead/jhead+0x41c3bd)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/home/camsyn/bench/cov/jhead/jhead+0x42c39c) in bcmp
Exiting
```

# Steps to Reproduce
- Download the `jhead-3.06` source code with the official link and build it with MSan (`-fsanitize=memory`)
- Executing jhead (`jhead /path/to/input`) with the provided input files

**Comment by Matthias-Wandel** [comment]
Fixed by a8e4cc2454ec0d08dc823c8edc20e402f4c856fb
Or at least that should fix it.  the tools i have installed didn't actually report this error, but I could see how this could be triggered.

**Comment by Matthias-Wandel** [comment]
a8e4cc2454ec0d08dc823c8edc20e402f4c856fb
