### ISSUE TITLE
jhead: heap-buffer-overflow on jhead.c:1200 in ProcessFile

### ISSUE THREAD

**Issue by Shin-Yan** [Matthias-Wandel/jhead#81]
# Summary

An segmentation fault caused when using jhead.
AddressSanitizer reports it as heap-buffer-overflow

# Version or commit
```
$ git log --oneline -1
4d04ac9 (HEAD -> master, tag: 3.08, origin/master, origin/HEAD) Bumped version number to 3.08
```

# OS and Arch
```
Ubuntu 20.04.6 LTS
Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
```

# Steps to reproduce
## make
```
$ git clone https://github.com/Matthias-Wandel/jhead.git
$ cd jhead
$ export CFLAGS='-fsanitize=address -fsanitize-recover=address -g3'
$ export CXXFLAGS='-fsanitize=address -fsanitize-recover=address -g3'
$ make
```

# AddressSanitizer report:
```
$ /home/fuzzer/sytseng/ASAN/jhead/jhead -mkexif -dsft ./poc_0

=================================================================
==296701==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60d0000000e4 at pc 0x7f15d633f58d bp 0x7ffe2a744750 sp 0x7ffe2a743ef8
WRITE of size 19 at 0x60d0000000e4 thread T0
    #0 0x7f15d633f58c in __interceptor_memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:790
    #1 0x55d4f82d8ab9 in memcpy /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34
    #2 0x55d4f82d8ab9 in ProcessFile jhead.c:1200
    #3 0x55d4f82d4077 in main jhead.c:1805
    #4 0x7f15d5f87082 in __libc_start_main ../csu/libc-start.c:308
    #5 0x55d4f82d51ed in _start (/home/fuzzer/sytseng/ASAN/jhead/jhead+0x111ed)

Address 0x60d0000000e4 is a wild pointer.
SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:790 in __interceptor_memcpy
Shadow bytes around the buggy address:
  0x0c1a7fff7fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c1a7fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c1a7fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c1a7fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c1a7fff8000: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
=>0x0c1a7fff8010: 00 00 00 00 00 00 00 00 06 fa fa fa[fa]fa fa fa
  0x0c1a7fff8020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1a7fff8030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1a7fff8040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1a7fff8050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c1a7fff8060: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==296701==ABORTING
```

**Comment by Matthias-Wandel** [comment]
Never was able to reproduce this years ago, and the test file is now missing.  Many change since, just clearing out old obsolete reports.
